version: '3.8'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch-konsicred
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - "xpack.security.enabled=false"
      - "xpack.security.http.ssl.enabled=false"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-konsicred
    environment:
      RABBITMQ_DEFAULT_USER: "konsicred"
      RABBITMQ_DEFAULT_PASS: "konsicred"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis-konsicred
    command: redis-server --requirepass konsicred
    ports:
      - "6379:6379"

  

  api-konsi:
    image: eriksena16/konsicred-web-api:latest
    container_name: konsiCred-web-api
    build:
      context: ../src
      dockerfile: ./Services/Konsi/KonsiCred.Api/Dockerfile
    restart: always
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5005
      - Elasticsearch__Uri=http://elasticsearch-konsicred:9200 
    depends_on:
      - elasticsearch
      - rabbitmq
      - redis
      

  web-konsi:
    image: eriksena16/konsicred-web-app:latest
    container_name: konsiCred-web-app
    build:
      context: ../src
      dockerfile: ./WebApps/KonsiCred.Web/KonsiCred.Web/Dockerfile
    restart: always   
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5006
      - ApiBaseUrl=http://konsiCred-web-api:5005
    depends_on:
      - api-konsi


volumes:
  elasticsearch-data:
    driver: local
