version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-konsicred
    environment:
      RABBITMQ_DEFAULT_USER: "konsicred"
      RABBITMQ_DEFAULT_PASS: "konsicred"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:latest
    container_name: redis-konsicred
    command: redis-server --requirepass konsicred
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch-konsicred
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - "elasticnetwork"
   
    

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana-konsicred
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      -  ELASTICSEARCH_HOSTS=http://elasticsearch:9200
     networks:
      - "elasticnetwork"

  api-konsi:
    image: eriksena16/konsicred-web-api:latest
    container_name: konsiCred-web-api
    build:
      context: ../src
      dockerfile: ./Services/Konsi/KonsiCred.Api/Dockerfile
    restart: always   
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5005
    depends_on:
      - rabbitmq
      - redis
      - elasticsearch
networks:
  elasticsearch:
    driver: bridge

volumes:
  elasticsearch-data: